pass ISelectionContext to VoxelShape getters
TheCBProject/CBMultipart pull request #86
Opened 2021-06-04 08:35 UTC by MrTJP

MergedVoxelShapeHolder now accepts an extractor function as needed instead of having one cached. I only saw TileMultipart use this class, but if its used elsewhere and pre-setting the extractor is required, I can un-deprecate the setters and original non-extractor aware function.

2021-06-04 10:18 UTC, covers1624 requested changes

2021-06-04 10:18 UTC, covers1624 commented on src/main/scala/codechicken/multipart/api/part/TMultiPart.scala
> +    def getSupportShape: VoxelShape = getOutlineShape(ISelectionContext.empty)
This should be named `getBlockSupportShape` and should call `getCollisionShape` to be inline with `AbstractBlock`.

2021-06-04 10:18 UTC, covers1624 commented on src/main/scala/codechicken/multipart/api/part/TMultiPart.scala
> +    def getOutlineShape(context:ISelectionContext): VoxelShape = VoxelShapes.empty()
This should be renamed to `getShape`

2021-06-04 10:18 UTC, covers1624 commented on src/main/scala/codechicken/multipart/api/part/TMultiPart.scala
> +    def getRenderOcclusionShape: VoxelShape = getOutlineShape(ISelectionContext.empty)
This should be renamed to 'getOcclusionShape', however, might conflict with other things.

2021-06-04 10:18 UTC, covers1624 commented on src/main/scala/codechicken/multipart/api/part/TMultiPart.scala
> +    def getVisualShape(context: ISelectionContext): VoxelShape = getOutlineShape(context)
This should call `getCollisionShape` to be inline with `AbstractBlock`.

2021-06-04 10:18 UTC, covers1624 commented on src/main/scala/codechicken/multipart/block/TileMultiPart.java
> +    public VoxelShape getVisualShape(ISelectionContext context) { return visualShapeHolder.update(partList, part -> part.getVisualShape(context)); }
These are missing CCL changes, we should discuss how to handle caching of these with ISelectionContext's properly.

2021-06-04 10:18 UTC, covers1624 commented on src/main/scala/codechicken/multipart/minecraft/McStatePart.java
This class should override `getBlockSupportShape` and `getVisualShape`.

2021-06-04 10:18 UTC, covers1624 commented on src/main/scala/codechicken/multipart/minecraft/McStatePart.java
>          return state.getCollisionShape(world(), pos());
This should have `context` passed through to the state.

2021-06-04 10:18 UTC, covers1624 commented on src/main/scala/codechicken/multipart/minecraft/McStatePart.java
>          return state.getShape(world(), pos());
This should have `context` passed through to the state.

2021-06-04 19:12 UTC, MrTJP commented
Addressed comments, still not ready for merge. Also forgot the version bump, will do that next push

2021-06-05 07:24 UTC, covers1624 commented
After some more thought on `getRenderOcclusionShape`, I think we should keep its name as-is. `getOcclusionShape` is used for part-part occlusion at the moment, being able to control both independently is important.

2021-06-05 07:28 UTC, covers1624 requested changes
Looks good!
This should definitely suffice for now, minor change, and that version bump needed.

2021-06-05 07:28 UTC, covers1624 commented on src/main/scala/codechicken/multipart/util/MergedVoxelShapeHolder.java
> +    private Function<T, VoxelShape> extractor;
This can be removed as it's a new class to this project.

2021-06-17 17:45 UTC, MrTJP commented
Sorry for the late follow up. It turns out, the tiles not loading issue is not caused by this commit. Seems like they are not syncing to the client on world load for some reason. Serverside, `loadParts` is being called properly, and I can see the appropriate parts being filled out.

We can merge this in now. I'll investigate the loading issue separately.

2021-06-18 04:47 UTC, covers1624 approved these changes

2021-06-18 04:47 UTC, merged